// package translations contains message translations of each defined language.
//
// Most of the code and data are generated by gotext.
// Howto: see https://www.alexedwards.net/blog/i18n-managing-translations.
// The workflow for adding or updating a translation goes like this:
//
//  1. Generate the out.gotext.json files containing the messages which need to be translated by running the go generate command below.
//  2. Copy each generated out.gotext.json to messages.gotext.json.
//  3. Edits the messages.gotext.json to fill the necessary translations.
//  4. Run go generate again, to generate/update the catalog.go file.
//  5. Commit these updated files with the name messages.gotext.json in the folder for the appropriate language.
package translations

//go:generate gotext -srclang=en-US update -out=catalog.go -lang=en-US,zh-CN,de-DE looz.ws/typstify
